# -*- coding: utf-8 -*-
"""Codes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16crMTo72TLqR9Xzz9RT8wTBmyc1UUmeN
"""

import random

def roll_die():
    return random.randint(1, 6)

def simulate_rolls(target, rolls):
    target_count = 0
    roll_counts = [0] * 6

    for _ in range(rolls):
        result = roll_die()
        roll_counts[result - 1] += 1
        if result == target:
            target_count += 1

    probability = target_count / rolls

    print(f"Probability of rolling a {target}: {probability:.2f}")
    print("Roll counts for each number:")
    for i in range(1, 7):
        print(f"  {i}: {roll_counts[i - 1]}")

target_number = int(input("Enter the target number (1 to 6): "))
total_rolls = int(input("Enter the number of rolls: "))

simulate_rolls(target=target_number, rolls=total_rolls)

import random

def calculate_conditional_probability(num_rolls):
    """Calculate the probability that the sum is 7 given that one die shows 4."""
    count_A_and_B = 0  # Count of (sum is 7 and one die shows 4)
    count_B = 0        # Count of (one die shows 4)

    for _ in range(num_rolls):
        die1 = random.randint(1, 6)
        die2 = random.randint(1, 6)

        # Check if at least one die is 4
        if die1 == 4 or die2 == 4:
            count_B += 1
            # Check if the sum is 7
            if die1 + die2 == 7:
                count_A_and_B += 1

    # Calculate conditional probability P(A|B)
    return count_A_and_B / count_B if count_B > 0 else 0

def main():
    try:
        num_rolls = int(input("Enter the number of rolls to simulate: "))
        if num_rolls <= 0:
            print("Please enter a positive integer for the number of rolls.")
            return
        conditional_prob = calculate_conditional_probability(num_rolls)
        print(f"The conditional probability P(A|B) is: {conditional_prob:.4f}")
    except ValueError:
        print("Invalid input. Please enter an integer.")

if __name__ == "__main__":
    main()

import numpy as np  # Import the NumPy library for numerical operations

# Function to check the independence of two events A and B
def check_independence(A, B):
    # Calculate probabilities
    P_A = np.mean(A)  # Probability of A (mean of values in A)
    P_B = np.mean(B)  # Probability of B (mean of values in B)
    P_A_and_B = np.mean(A * B)  # Joint probability of A and B (mean of the product A * B)

    # Check independence condition: P(A and B) ≈ P(A) * P(B)
    independence_condition = np.isclose(P_A_and_B, P_A * P_B)  # Use np.isclose for floating-point comparisons

    # Display results
    print(f"P(A): {P_A:.4f}")  # Print probability of A with 4 decimal places
    print(f"P(B): {P_B:.4f}")  # Print probability of B with 4 decimal places
    print(f"P(A and B): {P_A_and_B:.4f}")  # Print joint probability of A and B
    print(f"P(A) * P(B): {P_A * P_B:.4f}")  # Print product of probabilities
    print(f"Are A and B independent? {'Yes' if independence_condition else 'No'}")  # Print whether A and B are independent

# Main function to execute the program
def main():
    # Get the number of samples from the user
    n_samples = int(input("Enter the number of samples: "))

    # Prompt the user to enter values for event A
    print("Enter values for event A (space-separated, 0s and 1s):")
    A = np.array(list(map(int, input().split())))  # Convert input string to a NumPy array of integers

    # Prompt the user to enter values for event B
    print("Enter values for event B (space-separated, 0s and 1s):")
    B = np.array(list(map(int, input().split())))  # Convert input string to a NumPy array of integers

    # Check if the input lengths match the expected number of samples
    if len(A) != n_samples or len(B) != n_samples:
        print("Error: The number of samples does not match the input length.")  # Display an error if lengths don't match
        return  # Exit the function if there's an error

    # Call the function to check independence
    check_independence(A, B)

# Ensure the script runs only when executed directly (not when imported)
if __name__ == "__main__":
    main()

import numpy as np
import matplotlib.pyplot as plt

# Define a discrete random variable (Die Roll)
X = np.arange(1, 7)
P_X = np.ones(6) / 6  # Equal probability for each face of a die

# Calculate expected value (mean) and variance
expected_value = np.sum(X * P_X)
variance = np.sum((X - expected_value)**2 * P_X)
# Print results
print("Expected Value:", expected_value)
print("Variance:", variance)

# Plotting the PMF
plt.bar(X, P_X, color='blue')
plt.title('Probability Mass Function (Die Roll)')
plt.xlabel('Outcome')
plt.ylabel('Probability')
plt.show()